export default function () {
	return [
		{
			courseNumber: "1000",
			courseName: "Introduction to Microcomputers and Applications",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "1010",
			courseName: "Algorithmic Problem Solving",
			creditHours: 3,
			numberOfSections: 3,
		},
		{
			courseNumber: "1301",
			courseName: "Principles of Programming I",
			creditHours: 4,
			numberOfSections: 3,
		},
		{
			courseNumber: "1302",
			courseName: "Principles of Programming II",
			creditHours: 4,
			numberOfSections: 2,
		},
		{
			courseNumber: "1340",
			courseName: "Computing for Scientists",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "2620",
			courseName: "Discrete Structures",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "3101",
			courseName: "Computer Organization",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "3300",
			courseName: "UNIX Programming",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "3335",
			courseName: "The C Programming Language",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "3340",
			courseName: "Web Programming",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "3410",
			courseName: "Data Structures",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "3520",
			courseName: "Algorithms",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4121",
			courseName: "Data Communications and Networks I",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4321",
			courseName: "Software Engineering I",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4330",
			courseName: "Theory of Programming Languages",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4345",
			courseName: "Operating Systems",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4500",
			courseName: "Formal Languages and Automata Theory",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4721",
			courseName: "Database Design I",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4820",
			courseName: "Artificial Intelligence",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4830",
			courseName: "Computer Graphics",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4840",
			courseName: "Full Stack Web Programming",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4900",
			courseName: "Senior Seminar",
			creditHours: 3,
			numberOfSections: 1,
		},
		{
			courseNumber: "4990",
			courseName: "Topics in Computer Science",
			creditHours: 3,
			numberOfSections: 2,
		},
	];
}
